import { useSearchParams } from "react-router-dom";
import { useCallback, useMemo } from "react";

export type Language = "en" | "ar";

const DEFAULT_LANGUAGE: Language = "en";

const translations = {
  en: {
    // CourseCards
    "allCourses": "All Courses",
    "discoverCourses": "Discover our comprehensive collection of courses designed to help you grow, learn, and achieve your goals.",
    "allCategories": "All categories",
    "searchCourse": "Search Course",
    "loadingCourses": "Loading courses…",
    "noCoursesMatch": "No courses match your filters.",
    "noCoursesAvailable": "No courses available yet.",
    "viewCourse": "View Course",
    "lessons": "lessons",
    "lesson": "lesson",
    "noImage": "No image",
    "uncategorized": "Uncategorized",
    "noDescription": "No description available.",
    "previousPage": "Previous",
    "nextPage": "Next",

    // CoursePreview
    "backToCourseList": "Back to course list",
    "courseProgress": "Course progress",
    "lessonOf": "Lesson",
    "of": "of",
    "complete": "complete",
    "lessonsCompleted": "lessons completed",
    "previousLesson": "Previous Lesson",
    "nextLesson": "Next Lesson",
    "markComplete": "Mark Complete",
    "completed": "Completed",
    "overview": "Overview",
    "learningObjectives": "Learning Objectives",
    "lessonOverview": "Lesson Overview",
    "courseLessons": "Course lessons",
    "lessonPlaylist": "Lesson playlist",
    "done": "done",
    "publishLessons": "Publish lessons to make this course playable.",
    "aboutThisCourse": "About this course",
    "addShortDescription": "Add a short description to highlight the course story.",
    "courseMaterial": "Course material",
    "duration": "Duration",
    "noVideoAvailable": "No video available",
    "addVideoUrl": "Add a video URL to this lesson to embed it here.",
    "invalidCourseId": "Invalid course identifier.",
    "loadingCourse": "Loading course experience…",
    "checkingSubscription": "Checking subscription status…",
    "courseNotFound": "Course not found",
    "courseUnavailable": "The selected course is unavailable or has been removed.",
    "backToCourseListButton": "Back to course list",
    "premiumCourse": "Premium Course",
    "unlockFullProgram": "Unlock the full program to access every lesson.",
    "membershipRequired": "Membership required",
    "unlock": "Unlock",
    "yourInvestment": "Your investment",
    "per": "per",
    "plan": "Plan",
    "subscribeUnlock": "Subscribe & Unlock",
    "backToCourses": "Back to courses",
    "unlimitedStreaming": "Unlimited HD streaming of every lesson",
    "progressTracking": "Guided progress tracking and completion badges",
    "bonusResources": "Bonus resources and worksheets per lesson",
    "subscriptionStatus": "Your subscription is currently marked as",
    "activateSubscription": "Activate it to view every lesson for this course.",
    "activeSubscriptionDescription": "An active subscription lets you stream each lesson, track your progress, and download exclusive resources.",
    "subscriptionPricing": "Subscription pricing will appear here once configured. You can still manage your plan on the payments page.",
    "publishLessonsToStart": "Publish lessons to get started.",
    "month": "month",
    "year": "year",
    "week": "week",
    "day": "day",
    "min": "min",
    "hr": "hr",
    "hours": "hours",
    "hour": "hour",
    "minutes": "minutes",
    "minute": "minute",
    
    // UserDashboard
    "dashboard": "Dashboard",
    "welcomeBack": "Welcome back!",
    "coursesCompleted": "Courses Completed",
    "inProgress": "In Progress",
    "hoursWatched": "Hours Watched",
    "memberSince": "Member Since",
    "myCourses": "My Courses",
    "inProgressTab": "In Progress",
    "completedTab": "Completed",
    "noCoursesInProgress": "You don't have any courses in progress yet.",
    "noCoursesCompleted": "You haven't completed any courses yet.",
    "startLearning": "Start learning to see your progress here!",
    "getStarted": "Get Started",
    "noCoursesYet": "No courses yet",
    "getStartedDescription": "Start your learning journey by exploring our courses. Discover topics that interest you and begin your path to knowledge.",
    "browseCourses": "Browse Courses",
    
    // Navigation
    "home": "Home",
    "courses": "Courses",
    "subscription": "Subscription",
    
    // Payments
    "payments": "Payments",
    "manageSubscriptions": "Manage subscriptions and payment processing",
    "subscriptionStatusTitle": "Subscription Status",
    "syncing": "Syncing...",
    "yourSubscriptionInfo": "Your current subscription information",
    "syncingSubscriptionStatus": "Syncing subscription status from Stripe...",
    "noActiveSubscription": "You don't have an active subscription.",
    "subscribeNow": "Subscribe Now",
    "creatingCheckoutSession": "Creating checkout session...",
    "subscriptionActive": "Subscription Active",
    "subscriptionExpired": "Subscription Expired",
    "active": "Active",
    "trialing": "Trialing",
    "expired": "Expired",
    "pastDue": "Past Due",
    "canceled": "Canceled",
    "subscriptionDataNeedsSync": "Subscription Data Needs Sync",
    "subscriptionDatesInvalid": "The subscription dates are missing or invalid. Click the button below to sync the latest data from Stripe.",
    "syncFromStripe": "Sync from Stripe",
    "billingCycle": "Billing Cycle",
    "currentPeriod": "Current Period",
    "daysRemaining": "Days Remaining",
    "days": "days",
    "cycleProgress": "Cycle Progress",
    "daysElapsed": "days elapsed",
    "daysRemainingLabel": "days remaining",
    "scheduledForCancellation": "Scheduled for Cancellation",
    "subscriptionEndsOn": "Your subscription will end on",
    "canReactivateAnytime": "You can reactivate it anytime before then.",
    "reactivateSubscription": "Reactivate Subscription",
    "reactivating": "Reactivating...",
    "cancelSubscription": "Cancel Subscription",
    "manageInStripe": "Manage in Stripe",
    "opening": "Opening...",
    "manageInStripeDescription": "Use the \"Manage in Stripe\" button to update payment methods, view billing history, and manage your subscription settings.",
    "cancelSubscriptionTitle": "Cancel Subscription?",
    "subscriptionRemainsActive": "Your subscription will remain active until the end of the current billing period.",
    "continueAccessUntil": "You will continue to have access until",
    "canReactivateBeforePeriod": "You can reactivate your subscription at any time before the period ends.",
    "keepSubscription": "Keep Subscription",
    "canceling": "Canceling...",
    "productPriceManagement": "Product & Price Management",
    "adminOnly": "Admin Only",
    "configureStripeProduct": "Configure which Stripe product and price to use for subscriptions",
    "currentConfiguration": "Current Configuration",
    "product": "Product",
    "price": "Price",
    "fetchProductsFromStripe": "Fetch Products from Stripe",
    "fetchingFromStripe": "Fetching from Stripe...",
    "selectProduct": "Select Product",
    "chooseProduct": "Choose a product",
    "selectPrice": "Select Price",
    "choosePrice": "Choose a price",
    "noActiveRecurringPrices": "No active recurring prices found for this product.",
    "saveConfiguration": "Save Configuration",
    "saving": "Saving...",
    "noActiveProducts": "No active products found in Stripe. Create products in your Stripe dashboard first.",
    "subscribe": "Subscribe",
    "testSubscription": "Test Subscription",
    "testStripePaymentFlow": "Test the Stripe payment flow with a test subscription. This will redirect you to Stripe's checkout page.",
    "noProductConfigured": "No product configured. An admin needs to configure a product first.",
    "paymentSuccessfulActivated": "Payment successful! Your subscription has been activated.",
    "paymentSuccessfulActivating": "Payment successful! Your subscription is being activated...",
    "paymentSuccessfulSyncFailed": "Payment successful, but failed to sync subscription status. Please refresh the page.",
    "paymentCanceled": "Payment was canceled. You can try again anytime.",
    "failedToCreateCheckoutSession": "Failed to create checkout session",
    "failedToCreateCheckoutSessionRetry": "Failed to create checkout session. Please try again.",
    "failedToCancelSubscription": "Failed to cancel subscription. Please try again.",
    "failedToReactivateSubscription": "Failed to reactivate subscription. Please try again.",
    "failedToOpenCustomerPortal": "Failed to open customer portal",
    "failedToOpenCustomerPortalRetry": "Failed to open customer portal. Please try again.",
    "noSubscriptionFoundToSync": "No subscription found to sync",
    "subscriptionDataSyncedSuccessfully": "Subscription data synced successfully",
    "failedToSyncSubscription": "Failed to sync subscription. Please try again.",
    "failedToFetchProducts": "Failed to fetch products from Stripe",
    "pleaseSelectProductAndPrice": "Please select both a product and a price",
    "selectedProductOrPriceNotFound": "Selected product or price not found",
    "paymentSettingsSavedSuccessfully": "Payment settings saved successfully",
    "failedToSavePaymentSettings": "Failed to save payment settings",
    "for": "for",
    "noActivePrices": "No active prices",
    "subscribeToProduct": "Subscribe to {productName} for {price} per {interval}",
  },
  ar: {
    // CourseCards
    "allCourses": "جميع الدورات",
    "discoverCourses": "اكتشف مجموعتنا الشاملة من الدورات المصممة لمساعدتك على النمو والتعلم وتحقيق أهدافك.",
    "allCategories": "جميع الفئات",
    "searchCourse": "البحث عن دورة",
    "loadingCourses": "جاري تحميل الدورات…",
    "noCoursesMatch": "لا توجد دورات تطابق المرشحات الخاصة بك.",
    "noCoursesAvailable": "لا توجد دورات متاحة بعد.",
    "viewCourse": "عرض الدورة",
    "lessons": "دروس",
    "lesson": "درس",
    "noImage": "لا توجد صورة",
    "uncategorized": "غير مصنف",
    "noDescription": "لا يوجد وصف متاح.",
    "previousPage": "السابق",
    "nextPage": "التالي",

    // CoursePreview
    "backToCourseList": "العودة إلى قائمة الدورات",
    "courseProgress": "تقدم الدورة",
    "lessonOf": "الدرس",
    "of": "من",
    "complete": "مكتمل",
    "lessonsCompleted": "دروس مكتملة",
    "previousLesson": "الدرس السابق",
    "nextLesson": "الدرس التالي",
    "markComplete": "تحديد كمكتمل",
    "completed": "مكتمل",
    "overview": "نظرة عامة",
    "learningObjectives": "أهداف التعلم",
    "lessonOverview": "نظرة عامة على الدرس",
    "courseLessons": "دروس الدورة",
    "lessonPlaylist": "قائمة تشغيل الدروس",
    "done": "منجز",
    "publishLessons": "انشر الدروس لجعل هذه الدورة قابلة للتشغيل.",
    "aboutThisCourse": "حول هذه الدورة",
    "courseMaterial": "مادة الدورة",
    "addShortDescription": "أضف وصفًا قصيرًا لتسليط الضوء على قصة الدورة.",
    "duration": "المدة",
    "noVideoAvailable": "لا يوجد فيديو متاح",
    "addVideoUrl": "أضف رابط فيديو لهذا الدرس لتضمينه هنا.",
    "invalidCourseId": "معرف الدورة غير صالح.",
    "loadingCourse": "جاري تحميل تجربة الدورة…",
    "checkingSubscription": "جاري التحقق من حالة الاشتراك…",
    "courseNotFound": "الدورة غير موجودة",
    "courseUnavailable": "الدورة المحددة غير متاحة أو تم إزالتها.",
    "backToCourseListButton": "العودة إلى قائمة الدورات",
    "premiumCourse": "دورة مميزة",
    "unlockFullProgram": "افتح البرنامج الكامل للوصول إلى كل درس.",
    "membershipRequired": "عضوية مطلوبة",
    "unlock": "فتح",
    "yourInvestment": "استثمارك",
    "per": "لكل",
    "plan": "الخطة",
    "subscribeUnlock": "اشترك وافتح",
    "backToCourses": "العودة إلى الدورات",
    "unlimitedStreaming": "بث عالي الجودة غير محدود لكل درس",
    "progressTracking": "تتبع التقدم الموجه وشارات الإنجاز",
    "bonusResources": "موارد ومخططات إضافية لكل درس",
    "subscriptionStatus": "اشتراكك محدد حاليًا كـ",
    "activateSubscription": "قم بتنشيطه لعرض كل درس لهذه الدورة.",
    "activeSubscriptionDescription": "الاشتراك النشط يتيح لك بث كل درس وتتبع تقدمك وتنزيل الموارد الحصرية.",
    "subscriptionPricing": "سيظهر تسعير الاشتراك هنا بمجرد التكوين. لا يزال بإمكانك إدارة خطتك في صفحة المدفوعات.",
    "publishLessonsToStart": "انشر الدروس للبدء.",
    "month": "شهر",
    "year": "سنة",
    "week": "أسبوع",
    "day": "يوم",
    "min": "دقيقة",
    "hr": "ساعة",
    "hours": "ساعات",
    "hour": "ساعة",
    "minutes": "دقائق",
    "minute": "دقيقة",
    
    // UserDashboard
    "dashboard": "لوحة التحكم",
    "welcomeBack": "مرحباً بعودتك!",
    "coursesCompleted": "الدورات المكتملة",
    "inProgress": "قيد التنفيذ",
    "hoursWatched": "ساعات المشاهدة",
    "memberSince": "عضو منذ",
    "myCourses": "دوراتي",
    "inProgressTab": "قيد التنفيذ",
    "completedTab": "مكتملة",
    "noCoursesInProgress": "ليس لديك أي دورات قيد التنفيذ بعد.",
    "noCoursesCompleted": "لم تكمل أي دورات بعد.",
    "startLearning": "ابدأ التعلم لرؤية تقدمك هنا!",
    "getStarted": "ابدأ",
    "noCoursesYet": "لا توجد دورات بعد",
    "getStartedDescription": "ابدأ رحلة التعلم الخاصة بك من خلال استكشاف دوراتنا. اكتشف الموضوعات التي تهمك وابدأ طريقك نحو المعرفة.",
    "browseCourses": "تصفح الدورات",
    
    // Navigation
    "home": "الرئيسية",
    "courses": "الدورات",
    "subscription": "الاشتراك",
    
    // Payments
    "payments": "المدفوعات",
    "manageSubscriptions": "إدارة الاشتراكات ومعالجة المدفوعات",
    "subscriptionStatusTitle": "حالة الاشتراك",
    "syncing": "جاري المزامنة...",
    "yourSubscriptionInfo": "معلومات الاشتراك الحالية",
    "syncingSubscriptionStatus": "جاري مزامنة حالة الاشتراك من Stripe...",
    "noActiveSubscription": "ليس لديك اشتراك نشط.",
    "subscribeNow": "اشترك الآن",
    "creatingCheckoutSession": "جاري إنشاء جلسة الدفع...",
    "subscriptionActive": "الاشتراك نشط",
    "subscriptionExpired": "الاشتراك منتهي",
    "active": "نشط",
    "trialing": "تجريبي",
    "expired": "منتهي",
    "pastDue": "متأخر",
    "canceled": "ملغى",
    "subscriptionDataNeedsSync": "بيانات الاشتراك تحتاج للمزامنة",
    "subscriptionDatesInvalid": "تواريخ الاشتراك مفقودة أو غير صالحة. انقر على الزر أدناه لمزامنة أحدث البيانات من Stripe.",
    "syncFromStripe": "مزامنة من Stripe",
    "billingCycle": "دورة الفوترة",
    "currentPeriod": "الفترة الحالية",
    "daysRemaining": "الأيام المتبقية",
    "days": "أيام",
    "cycleProgress": "تقدم الدورة",
    "daysElapsed": "أيام منقضية",
    "daysRemainingLabel": "أيام متبقية",
    "scheduledForCancellation": "مجدول للإلغاء",
    "subscriptionEndsOn": "سينتهي اشتراكك في",
    "canReactivateAnytime": "يمكنك إعادة تفعيله في أي وقت قبل ذلك.",
    "reactivateSubscription": "إعادة تفعيل الاشتراك",
    "reactivating": "جاري إعادة التفعيل...",
    "cancelSubscription": "إلغاء الاشتراك",
    "manageInStripe": "إدارة في Stripe",
    "opening": "جاري الفتح...",
    "manageInStripeDescription": "استخدم زر \"إدارة في Stripe\" لتحديث طرق الدفع وعرض سجل الفوترة وإدارة إعدادات الاشتراك الخاصة بك.",
    "cancelSubscriptionTitle": "إلغاء الاشتراك؟",
    "subscriptionRemainsActive": "سيظل اشتراكك نشطًا حتى نهاية فترة الفوترة الحالية.",
    "continueAccessUntil": "ستستمر في الحصول على الوصول حتى",
    "canReactivateBeforePeriod": "يمكنك إعادة تفعيل اشتراكك في أي وقت قبل انتهاء الفترة.",
    "keepSubscription": "الاحتفاظ بالاشتراك",
    "canceling": "جاري الإلغاء...",
    "productPriceManagement": "إدارة المنتج والسعر",
    "adminOnly": "للمشرف فقط",
    "configureStripeProduct": "تكوين منتج وسعر Stripe المراد استخدامهما للاشتراكات",
    "currentConfiguration": "التكوين الحالي",
    "product": "المنتج",
    "price": "السعر",
    "fetchProductsFromStripe": "جلب المنتجات من Stripe",
    "fetchingFromStripe": "جاري الجلب من Stripe...",
    "selectProduct": "اختر المنتج",
    "chooseProduct": "اختر منتجًا",
    "selectPrice": "اختر السعر",
    "choosePrice": "اختر سعرًا",
    "noActiveRecurringPrices": "لا توجد أسعار متكررة نشطة لهذا المنتج.",
    "saveConfiguration": "حفظ التكوين",
    "saving": "جاري الحفظ...",
    "noActiveProducts": "لا توجد منتجات نشطة في Stripe. أنشئ المنتجات في لوحة تحكم Stripe أولاً.",
    "subscribe": "اشترك",
    "testSubscription": "اشتراك تجريبي",
    "testStripePaymentFlow": "اختبر عملية الدفع في Stripe مع اشتراك تجريبي. سيتم إعادة توجيهك إلى صفحة الدفع في Stripe.",
    "noProductConfigured": "لم يتم تكوين منتج. يحتاج المشرف إلى تكوين منتج أولاً.",
    "paymentSuccessfulActivated": "تم الدفع بنجاح! تم تفعيل اشتراكك.",
    "paymentSuccessfulActivating": "تم الدفع بنجاح! جاري تفعيل اشتراكك...",
    "paymentSuccessfulSyncFailed": "تم الدفع بنجاح، ولكن فشلت مزامنة حالة الاشتراك. يرجى تحديث الصفحة.",
    "paymentCanceled": "تم إلغاء الدفع. يمكنك المحاولة مرة أخرى في أي وقت.",
    "failedToCreateCheckoutSession": "فشل إنشاء جلسة الدفع",
    "failedToCreateCheckoutSessionRetry": "فشل إنشاء جلسة الدفع. يرجى المحاولة مرة أخرى.",
    "failedToCancelSubscription": "فشل إلغاء الاشتراك. يرجى المحاولة مرة أخرى.",
    "failedToReactivateSubscription": "فشل إعادة تفعيل الاشتراك. يرجى المحاولة مرة أخرى.",
    "failedToOpenCustomerPortal": "فشل فتح بوابة العملاء",
    "failedToOpenCustomerPortalRetry": "فشل فتح بوابة العملاء. يرجى المحاولة مرة أخرى.",
    "noSubscriptionFoundToSync": "لم يتم العثور على اشتراك للمزامنة",
    "subscriptionDataSyncedSuccessfully": "تمت مزامنة بيانات الاشتراك بنجاح",
    "failedToSyncSubscription": "فشلت مزامنة الاشتراك. يرجى المحاولة مرة أخرى.",
    "failedToFetchProducts": "فشل جلب المنتجات من Stripe",
    "pleaseSelectProductAndPrice": "يرجى اختيار المنتج والسعر معًا",
    "selectedProductOrPriceNotFound": "المنتج أو السعر المحدد غير موجود",
    "paymentSettingsSavedSuccessfully": "تم حفظ إعدادات الدفع بنجاح",
    "failedToSavePaymentSettings": "فشل حفظ إعدادات الدفع",
    "for": "لـ",
    "noActivePrices": "لا توجد أسعار نشطة",
    "subscribeToProduct": "اشترك في {productName} مقابل {price} لكل {interval}",
  },
} as const;

export function useLanguage() {
  const [searchParams, setSearchParams] = useSearchParams();
  
  const language = useMemo<Language>(() => {
    const lang = searchParams.get("lang");
    return lang === "ar" ? "ar" : DEFAULT_LANGUAGE;
  }, [searchParams]);

  const setLanguage = useCallback(
    (lang: Language) => {
      const newParams = new URLSearchParams(searchParams);
      if (lang === DEFAULT_LANGUAGE) {
        newParams.delete("lang");
      } else {
        newParams.set("lang", lang);
      }
      setSearchParams(newParams, { replace: true });
    },
    [searchParams, setSearchParams]
  );

  const t = useCallback(
    (key: keyof typeof translations.en): string => {
      return translations[language][key] || translations.en[key];
    },
    [language]
  );

  const translateInterval = useCallback(
    (interval: string): string => {
      const normalizedInterval = interval.toLowerCase();
      const key = normalizedInterval as keyof typeof translations.en;
      if (key in translations.en) {
        return translations[language][key];
      }
      return interval; // Fallback to original if not found
    },
    [language]
  );

  return {
    language,
    setLanguage,
    t,
    translateInterval,
    isRTL: language === "ar",
  };
}

