import { useSearchParams } from "react-router-dom";
import { useCallback, useMemo } from "react";
import { getLocalizedSiteUrl } from "@/lib/siteUrl";

export type Language = "en" | "ar";

const DEFAULT_LANGUAGE: Language = "en";

const translations = {
  en: {
    // CourseCards
    "allCourses": "All Courses",
    "discoverCourses": "Discover our comprehensive collection of courses designed to help you grow, learn, and achieve your goals.",
    "allCategories": "All categories",
    "allCoaches": "All coaches",
    "searchCourse": "Search Course",
    "loadingCourses": "Loading courses…",
    "noCoursesMatch": "No courses match your filters.",
    "noCoursesAvailable": "No courses available yet.",
    "viewCourse": "View Course",
    "lessons": "lessons",
    "lesson": "lesson",
    "noImage": "No image",
    "uncategorized": "Uncategorized",
    "noDescription": "No description available.",
    "previousPage": "Previous",
    "nextPage": "Next",

    // CoursePreview
    "backToCourseList": "Back to course list",
    "courseProgress": "Course progress",
    "lessonOf": "Lesson",
    "of": "of",
    "complete": "complete",
    "lessonsCompleted": "lessons completed",
    "previousLesson": "Previous Lesson",
    "nextLesson": "Next Lesson",
    "markComplete": "Mark Complete",
    "completed": "Completed",
    "overview": "Overview",
    "learningObjectives": "Learning Objectives",
    "lessonOverview": "Lesson Overview",
    "courseLessons": "Course lessons",
    "lessonPlaylist": "Lesson playlist",
    "done": "done",
    "publishLessons": "Publish lessons to make this course playable.",
    "aboutThisCourse": "About this course",
    "addShortDescription": "Add a short description to highlight the course story.",
    "courseMaterial": "Course material",
    "duration": "Duration",
    "noVideoAvailable": "No video available",
    "addVideoUrl": "Add a video URL to this lesson to embed it here.",
    "invalidCourseId": "Invalid course identifier.",
    "loadingCourse": "Loading course experience…",
    "checkingSubscription": "Checking subscription status…",
    "courseNotFound": "Course not found",
    "courseUnavailable": "The selected course is unavailable or has been removed.",
    "backToCourseListButton": "Back to course list",
    "premiumCourse": "Premium Course",
    "unlockFullProgram": "Unlock the full program to access every lesson.",
    "membershipRequired": "Membership required",
    "unlock": "Unlock",
    "yourInvestment": "Your investment",
    "per": "per",
    "plan": "Plan",
    "subscribeUnlock": "Subscribe & Unlock",
    "backToCourses": "Back to courses",
    "fullAccessAllCourses": "Full access to all courses",
    "liveMeetingsWithReham": "Attend live meetings with Reham",
    "audioOnlyMode": "Audio-only mode playback",
    "multiDeviceSupport": "Multi-device support",
    "periodicNewContent": "Periodic new content",
    "joinRehamDivaCommunity": "Join Reham Diva community",
    "trainingNotes": "Training notes",
    "subscriptionStatus": "Your subscription is currently marked as",
    "activateSubscription": "Activate it to view every lesson for this course.",
    "activeSubscriptionDescription": "An active subscription lets you stream each lesson, track your progress, and download exclusive resources.",
    "subscriptionPricing": "Subscription pricing will appear here once configured. You can still manage your plan on the payments page.",
    "packagePaywallSubscribeDescription": "Choose a plan that includes this course to unlock every lesson.",
    "packagePaywallUpgradeDescription": "Your current plan does not include this course. Upgrade to a plan that does.",
    "packagePaywallComparePlans": "Compare plans",
    "packagePaywallCompareDescription": "See how each plan compares for {course}. Review pricing, included content, and features side by side.",
    "packagePaywallCompareDetailsHeading": "Full plan details",
    "packagePaywallUpgrade": "Upgrade",
    "packagePaywallCurrentPlan": "Current plan",
    "packagePaywallUnavailable": "Unavailable",
    "packagePaywallNoPlans": "No subscription plans are available for this course yet.",
    "packagePaywallCheckoutError": "Unable to start checkout. Please try again.",
    "packagePaywallFeatureCourses": "Access to courses included in your plan",
    "billingModelLegacy": "Legacy",
    "billingModelPackages": "Packages",
    "migrateNoPlanUsers": "Migrate no-plan users",
    "migrateNoPlanUsersDescription": "Move users without an active subscription to the package billing model.",
    "migrateNoPlanUsersSuccess": "Users migrated to package billing.",
    "migrationStatsLegacy": "Legacy users",
    "migrationStatsPackages": "Package users",
    "migrationStatsEligible": "Eligible for migration",
    "paymentsPackagePlansTitle": "Subscription plans",
    "paymentsPackagePlansDescription": "Choose the plan that fits you. Compare features and subscribe in one click.",
    "paymentsPackageSubscribeHeading": "Pick a plan to get started.",
    "paymentsPackageUpgradeHeading": "Upgrade your plan to unlock more courses.",
    "publishLessonsToStart": "Publish lessons to get started.",
    "month": "month",
    "year": "year",
    "week": "week",
    "day": "day",
    "min": "min",
    "hr": "hr",
    "hours": "hours",
    "hour": "hour",
    "minutes": "minutes",
    "minute": "minute",
    
    // UserDashboard
    "dashboard": "Dashboard",
    "welcomeBack": "Welcome back!",
    "coursesCompleted": "Courses Completed",
    "inProgress": "In Progress",
    "hoursWatched": "Hours Watched",
    "memberSince": "Member Since",
    "myCourses": "My Courses",
    "inProgressTab": "In Progress",
    "completedTab": "Completed",
    "noCoursesInProgress": "You don't have any courses in progress yet.",
    "noCoursesCompleted": "You haven't completed any courses yet.",
    "startLearning": "Start learning to see your progress here!",
    "getStarted": "Get Started",
    "noCoursesYet": "No courses yet",
    "getStartedDescription": "Start your learning journey by exploring our courses. Discover topics that interest you and begin your path to knowledge.",
    "browseCourses": "Browse Courses",
    
    // Navigation
    "home": "Home",
    "courses": "Courses",
    "subscription": "Subscription",
    "personalTests": "Personal Tests",
    "personalTestsPageTitle": "Discover the Right Programs for You",
    "personalTestsPageSubtitle": "Take a short test and get personalized program recommendations based on your needs.",
    "searchPersonalTests": "Search tests…",
    "searchMyResults": "Search your results…",
    "noCompletedTestsMatch": "No completed tests match your search.",
    "recommendedCourseSingular": "recommended course",
    "recommendedCoursesCount": "recommended courses",
    "noPersonalTestsAvailable": "No tests are available right now. Check back soon.",
    "startPersonalTest": "Start Test",
    "testDescription": "Description",
    "question": "Question",
    "questions": "Questions",
    "personalTestNotAvailable": "This test is not available.",
    "backToPersonalTests": "Back to tests",
    "recommendedCourses": "Your recommended courses",
    "testCompletedTitle": "You've completed the test!",
    "testCompletedSubtitle": "Based on your answers, here are the courses that can help you the most.",
    "topRecommendedCourses": "Top Recommended Courses For You",
    "completedIn": "Completed in {duration}",
    "exploreAllCourses": "Explore All Courses",
    "chooseOneAnswer": "Choose one",
    "chooseAllAnswers": "Choose all that apply",
    "previous": "Previous",
    "next": "Next",
    "seeResults": "See results",
    "savingResults": "Saving your results…",
    "noCourseRecommendations": "No course recommendations matched your answers.",
    "retakeTest": "Retake test",
    "takeTests": "Take Tests",
    "availableTestsTab": "Available tests",
    "myResultsTab": "My results",
    "noCompletedTests": "You haven't completed any tests yet.",
    "viewResults": "View results",
    "completedOn": "Completed",
    "yourAnswers": "Your answers",
    "selectedAnswer": "Selected answer",
    "selectedAnswers": "Selected answers",
    "noAnswerSelected": "No answer selected.",
    "questionProgress": "Question {current} of {total}",
    "testProgressComplete": "{percent}% Complete",
    "basedOnAnswersTo": "Based on your answers to \"{testName}\"",
    "loading": "Loading…",

    // UserProfile dropdown
    "user": "User",
    "changePassword": "Change Password",
    "version": "Version",
    "build": "Build",
    "signOut": "Sign out",
    "signingOut": "Signing out…",
    "newPassword": "New Password",
    "confirmNewPassword": "Confirm New Password",
    "enterNewPassword": "Enter new password",
    "confirmNewPasswordPlaceholder": "Confirm new password",
    "cancel": "Cancel",
    "changing": "Changing…",
    "pleaseFillPasswordFields": "Please fill in all password fields",
    "passwordsDoNotMatch": "New passwords do not match",
    "passwordMinLength": "Password must be at least 8 characters long",
    "passwordChangedSuccess": "Password changed successfully",
    "failedToChangePassword": "Failed to change password. Please try again.",
    
    // Payments
    "payments": "Payments",
    "manageSubscriptions": "Manage subscriptions and payment processing",
    "subscriptionStatusTitle": "Subscription Status",
    "syncing": "Syncing...",
    "yourSubscriptionInfo": "Your current subscription information",
    "syncingSubscriptionStatus": "Syncing subscription status from Stripe...",
    "noActiveSubscription": "You don't have an active subscription.",
    "subscribeNow": "Subscribe Now",
    "creatingCheckoutSession": "Creating checkout session...",
    "subscriptionActive": "Subscription Active",
    "subscriptionExpired": "Subscription Expired",
    "active": "Active",
    "trialing": "Trialing",
    "expired": "Expired",
    "pastDue": "Past Due",
    "canceled": "Canceled",
    "subscriptionDataNeedsSync": "Subscription Data Needs Sync",
    "subscriptionDatesInvalid": "The subscription dates are missing or invalid. Click the button below to sync the latest data from Stripe.",
    "syncFromStripe": "Sync from Stripe",
    "billingCycle": "Billing Cycle",
    "currentPeriod": "Current Period",
    "daysRemaining": "Days Remaining",
    "days": "days",
    "cycleProgress": "Cycle Progress",
    "daysElapsed": "days elapsed",
    "daysRemainingLabel": "days remaining",
    "scheduledForCancellation": "Scheduled for Cancellation",
    "subscriptionEndsOn": "Your subscription will end on",
    "canReactivateAnytime": "You can reactivate it anytime before then.",
    "reactivateSubscription": "Reactivate Subscription",
    "reactivating": "Reactivating...",
    "cancelSubscription": "Cancel Subscription",
    "manageInStripe": "Manage in Stripe",
    "opening": "Opening...",
    "manageInStripeDescription": "Use the \"Manage in Stripe\" button to update payment methods, view billing history, and manage your subscription settings.",
    "cancelSubscriptionTitle": "Cancel Subscription?",
    "subscriptionRemainsActive": "Your subscription will remain active until the end of the current billing period.",
    "continueAccessUntil": "You will continue to have access until",
    "canReactivateBeforePeriod": "You can reactivate your subscription at any time before the period ends.",
    "keepSubscription": "Keep Subscription",
    "canceling": "Canceling...",
    "productPriceManagement": "Product & Price Management",
    "subscriptionPlansTitle": "Subscription Plans",
    "subscriptionPlansSubtitle": "Manage pricing plans, course access, and preview how they appear to users.",
    "createPlan": "Create Plan",
    "pricingPreview": "Pricing preview",
    "editPlan": "Edit plan",
    "createSubscriptionPlan": "Create subscription plan",
    "planBasics": "Basics",
    "planAppearance": "Appearance",
    "planCourseAccess": "Course access",
    "planInheritance": "Inheritance",
    "planFeatures": "Features",
    "planLivePreview": "Live preview",
    "planBadgeNone": "None",
    "planBadgeStartHere": "Start Here",
    "planBadgeBestValue": "Best Value",
    "planBadgeMostPopular": "Most Popular",
    "planBadgeLimited": "Limited",
    "planBadgeVip": "VIP",
    "planIncludeAllCourses": "Include all published courses",
    "planIncludeFromPlan": "Include everything from plan",
    "planUpdatePriceStripe": "Update price on Stripe",
    "planArchive": "Archive plan",
    "planSaveChanges": "Save changes",
    "planCompareAtPrice": "Compare-at price (optional)",
    "planPriceSubtitle": "Price subtitle",
    "planPromotionBadge": "Promotion badge",
    "planRibbonText": "Ribbon text (optional)",
    "planChecklistItem": "Mark as checklist item (for future admin fulfillment)",
    "planAddFeature": "Add feature",
    "adminOnly": "Admin Only",
    "configureStripeProduct": "Configure which Stripe product and price to use for subscriptions",
    "currentConfiguration": "Current Configuration",
    "product": "Product",
    "price": "Price",
    "fetchProductsFromStripe": "Fetch Products from Stripe",
    "fetchingFromStripe": "Fetching from Stripe...",
    "selectProduct": "Select Product",
    "chooseProduct": "Choose a product",
    "selectPrice": "Select Price",
    "choosePrice": "Choose a price",
    "selectMonthlyPrice": "Select Monthly Price",
    "chooseMonthlyPrice": "Choose a monthly price",
    "selectYearlyPrice": "Select Yearly Price",
    "chooseYearlyPrice": "Choose a yearly price",
    "monthlyPrice": "Monthly Price",
    "yearlyPrice": "Yearly Price",
    "monthly": "month",
    "yearly": "year",
    "none": "None",
    "optional": "optional",
    "noMonthlyPrices": "No monthly prices found for this product.",
    "noYearlyPrices": "No yearly prices found for this product.",
    "pleaseSelectProductAndMonthlyPrice": "Please select a product and monthly price",
    "noActiveRecurringPrices": "No active recurring prices found for this product.",
    "saveConfiguration": "Save Configuration",
    "saving": "Saving...",
    "noActiveProducts": "No active products found in Stripe. Create products in your Stripe dashboard first.",
    "subscribe": "Subscribe",
    "testSubscription": "Test Subscription",
    "testStripePaymentFlow": "Test the Stripe payment flow with a test subscription. This will redirect you to Stripe's checkout page.",
    "noProductConfigured": "No product configured. An admin needs to configure a product first.",
    "paymentSuccessfulActivated": "Payment successful! Your subscription has been activated.",
    "paymentSuccessfulActivating": "Payment successful! Your subscription is being activated...",
    "paymentSuccessfulSyncFailed": "Payment successful, but failed to sync subscription status. Please refresh the page.",
    "paymentCanceled": "Payment was canceled. You can try again anytime.",
    "failedToCreateCheckoutSession": "Failed to create checkout session",
    "failedToCreateCheckoutSessionRetry": "Failed to create checkout session. Please try again.",
    "failedToCancelSubscription": "Failed to cancel subscription. Please try again.",
    "failedToReactivateSubscription": "Failed to reactivate subscription. Please try again.",
    "failedToOpenCustomerPortal": "Failed to open customer portal",
    "failedToOpenCustomerPortalRetry": "Failed to open customer portal. Please try again.",
    "subscriptionAdminGrantedContactSupport": "Your subscription was granted by an admin. To change it, contact support.",
    "noSubscriptionFoundToSync": "No subscription found to sync",
    "subscriptionDataSyncedSuccessfully": "Subscription data synced successfully",
    "failedToSyncSubscription": "Failed to sync subscription. Please try again.",
    "failedToFetchProducts": "Failed to fetch products from Stripe",
    "pleaseSelectProductAndPrice": "Please select both a product and a price",
    "selectedProductOrPriceNotFound": "Selected product or price not found",
    "paymentSettingsSavedSuccessfully": "Payment settings saved successfully",
    "failedToSavePaymentSettings": "Failed to save payment settings",
    "for": "for",
    "noActivePrices": "No active prices",
    "subscribeToProduct": "Subscribe to {productName} for {price} per {interval}",
    "chooseBillingCycle": "Choose billing cycle",
    "mostPopular": "Most popular",
    "bestValue": "Best value",

    // Login
    "loginTitle": "Log in to Reham Diva",
    "loginCreateAccountTitle": "Create an account",
    "loginResetPasswordTitle": "Reset your password",
    "loginEnterResetCodeTitle": "Enter reset code",
    "loginWithGoogle": "Login with Google",
    "loginOr": "or",
    "loginEmail": "Email",
    "loginName": "Name",
    "loginPassword": "Password",
    "loginNewPassword": "New password",
    "loginResetCode": "Reset code",
    "loginForgotPassword": "Forgot your password?",
    "loginEmailPlaceholder": "alan.turing@example.com",
    "loginNamePlaceholder": "John Doe",
    "loginPasswordPlaceholder": "••••••••••••",
    "loginResetCodePlaceholder": "12345678",
    "loginSendingCode": "Sending code…",
    "loginSendResetCode": "Send reset code",
    "loginResettingPassword": "Resetting password…",
    "loginResetPassword": "Reset password",
    "loginRedirecting": "Redirecting…",
    "loginCreatingAccount": "Creating account…",
    "loginSigningIn": "Signing in…",
    "loginCreateAccount": "Create Account",
    "loginLogIn": "Log In",
    "loginResetEmailInfo": "If your email is registered with us, you'll receive a password reset email soon.",
    "loginResetCodeHint": "Enter the 8-digit code sent to {email}",
    "loginPasswordMinLength": "At least 8 characters",
    "loginPasswordUppercase": "One uppercase letter",
    "loginPasswordLowercase": "One lowercase letter",
    "loginPasswordNumber": "One number",
    "loginPasswordResetSuccess": "Password reset successful. Redirecting…",
    "loginAccountCreatedRedirecting": "Account created. Redirecting…",
    "loginSignedInRedirecting": "Signed in. Redirecting…",
    "loginNoAccount": "Don't have an account? ",
    "loginHasAccount": "Already have an account? ",
    "loginSignUp": "Sign up",
    "loginLogInLink": "Log in",
    "loginTermsPrefix": "By signing in, you agree to our ",
    "loginTerms": "Terms",
    "loginAnd": " and ",
    "loginPrivacyPolicy": "Privacy Policy",
    "loginErrorInvalidCredentials": "Invalid email or password. Please check your credentials and try again.",
    "loginErrorEmailNotFound": "No account found with this email address. Please check your email and try again.",
    "loginErrorWrongPassword": "Incorrect password. Please check your password and try again.",
    "loginErrorDeactivated": "This account has been deactivated. Please contact support for assistance.",
    "loginErrorUnauthorized": "You are not authorized to access this account. Please contact support.",
    "loginErrorEmailExists": "An account with this email already exists. Please sign in instead.",
    "loginErrorInvalidResetCode": "Invalid or expired reset code. Please check the code and try again, or request a new one.",
    "loginErrorResetCodeExpired": "The reset code has expired. Please request a new one.",
    "loginErrorSignInFailed": "Failed to sign in. Please check your email and password and try again.",
    "loginErrorRegisterFailed": "Failed to create account. Please try again or contact support if the problem persists.",
    "loginErrorGeneric": "An error occurred. Please try again or contact support if the problem persists.",
    "loginErrorUnexpected": "An unexpected error occurred. Please try again.",
    "loginErrorGoogleSignIn": "Failed to sign in with Google. Please try again.",
    "loginErrorPasswordRequirements": "Password does not meet requirements. Please check the password requirements above.",
    "loginErrorWrongResetCode": "Your reset code is incorrect.",
  },
  ar: {
    // CourseCards
    "allCourses": "جميع الدورات",
    "discoverCourses": "اكتشف مجموعتنا الشاملة من الدورات المصممة لمساعدتك على النمو والتعلم وتحقيق أهدافك.",
    "allCategories": "جميع الفئات",
    "allCoaches": "جميع المدربين",
    "searchCourse": "البحث عن دورة",
    "loadingCourses": "جاري تحميل الدورات…",
    "noCoursesMatch": "لا توجد دورات تطابق المرشحات الخاصة بك.",
    "noCoursesAvailable": "لا توجد دورات متاحة بعد.",
    "viewCourse": "عرض الدورة",
    "lessons": "دروس",
    "lesson": "درس",
    "noImage": "لا توجد صورة",
    "uncategorized": "غير مصنف",
    "noDescription": "لا يوجد وصف متاح.",
    "previousPage": "السابق",
    "nextPage": "التالي",

    // CoursePreview
    "backToCourseList": "العودة إلى قائمة الدورات",
    "courseProgress": "تقدم الدورة",
    "lessonOf": "الدرس",
    "of": "من",
    "complete": "مكتمل",
    "lessonsCompleted": "دروس مكتملة",
    "previousLesson": "الدرس السابق",
    "nextLesson": "الدرس التالي",
    "markComplete": "تحديد كمكتمل",
    "completed": "مكتمل",
    "overview": "نظرة عامة",
    "learningObjectives": "أهداف التعلم",
    "lessonOverview": "نظرة عامة على الدرس",
    "courseLessons": "دروس الدورة",
    "lessonPlaylist": "قائمة تشغيل الدروس",
    "done": "منجز",
    "publishLessons": "انشر الدروس لجعل هذه الدورة قابلة للتشغيل.",
    "aboutThisCourse": "حول هذه الدورة",
    "courseMaterial": "مادة الدورة",
    "addShortDescription": "أضف وصفًا قصيرًا لتسليط الضوء على قصة الدورة.",
    "duration": "المدة",
    "noVideoAvailable": "لا يوجد فيديو متاح",
    "addVideoUrl": "أضف رابط فيديو لهذا الدرس لتضمينه هنا.",
    "invalidCourseId": "معرف الدورة غير صالح.",
    "loadingCourse": "جاري تحميل تجربة الدورة…",
    "checkingSubscription": "جاري التحقق من حالة الاشتراك…",
    "courseNotFound": "الدورة غير موجودة",
    "courseUnavailable": "الدورة المحددة غير متاحة أو تم إزالتها.",
    "backToCourseListButton": "العودة إلى قائمة الدورات",
    "premiumCourse": "دورة مميزة",
    "unlockFullProgram": "اشتراكك يفتح لك جميع مواد الأنوثة وحب الذات مع رهام والانضمام إلى مجتمع رهام ديفا وحضور اللقاءات المباشرة مع رهام.",
    "membershipRequired": "عضوية مطلوبة",
    "unlock": "فتح",
    "yourInvestment": "استثمارك",
    "per": "لكل",
    "plan": "الخطة",
    "subscribeUnlock": "اشترك وافتح",
    "backToCourses": "العودة إلى الدورات",
    "fullAccessAllCourses": "وصول كامل لجميع الدورات",
    "liveMeetingsWithReham": "حضور لقاءات مباشرة مع رهام",
    "audioOnlyMode": "تشغيل وضع الصوت فقط",
    "multiDeviceSupport": "دعم متعدد الأجهزة الذكية",
    "periodicNewContent": "محتوى جديد بشكل دوري",
    "joinRehamDivaCommunity": "الانضمام لمجتمع رهام ديفا",
    "trainingNotes": "المذكرات التدريبية",
    "subscriptionStatus": "اشتراكك محدد حاليًا كـ",
    "activateSubscription": "قم بتنشيطه لعرض كل درس لهذه الدورة.",
    "activeSubscriptionDescription": "اشتراكك يفتح لك جميع مواد الأنوثة وحب الذات مع رهام والانضمام إلى مجتمع رهام ديفا وحضور اللقاءات المباشرة مع رهام",
    "subscriptionPricing": "سيظهر تسعير الاشتراك هنا بمجرد التكوين. لا يزال بإمكانك إدارة خطتك في صفحة المدفوعات.",
    "packagePaywallSubscribeDescription": "اختر خطة تتضمن هذا البرنامج لفتح جميع الدروس.",
    "packagePaywallUpgradeDescription": "خطتك الحالية لا تتضمن هذا البرنامج. قم بالترقية إلى خطة مناسبة.",
    "packagePaywallComparePlans": "قارن الخطط",
    "packagePaywallCompareDescription": "قارن الخطط المتاحة لـ {course}. راجع الأسعار والمحتوى المشمول والمزايا جنبًا إلى جنب.",
    "packagePaywallCompareDetailsHeading": "تفاصيل الخطط الكاملة",
    "packagePaywallUpgrade": "ترقية",
    "packagePaywallCurrentPlan": "الخطة الحالية",
    "packagePaywallUnavailable": "غير متاح",
    "packagePaywallNoPlans": "لا توجد خطط اشتراك متاحة لهذا البرنامج بعد.",
    "packagePaywallCheckoutError": "تعذر بدء الدفع. يرجى المحاولة مرة أخرى.",
    "packagePaywallFeatureCourses": "الوصول إلى البرامج المشمولة في خطتك",
    "billingModelLegacy": "قديم",
    "billingModelPackages": "باقات",
    "migrateNoPlanUsers": "ترحيل المستخدمين بدون خطة",
    "migrateNoPlanUsersDescription": "نقل المستخدمين بدون اشتراك نشط إلى نموذج الباقات.",
    "migrateNoPlanUsersSuccess": "تم ترحيل المستخدمين إلى نظام الباقات.",
    "migrationStatsLegacy": "مستخدمون بالنظام القديم",
    "migrationStatsPackages": "مستخدمون بالباقات",
    "migrationStatsEligible": "مؤهلون للترحيل",
    "paymentsPackagePlansTitle": "خطط الاشتراك",
    "paymentsPackagePlansDescription": "اختر الخطة المناسبة لك. قارن الميزات واشترك بضغطة واحدة.",
    "paymentsPackageSubscribeHeading": "اختر خطة للبدء.",
    "paymentsPackageUpgradeHeading": "رقِّ خطتك لفتح المزيد من البرامج.",
    "publishLessonsToStart": "انشر الدروس للبدء.",
    "month": "شهر",
    "year": "سنة",
    "week": "أسبوع",
    "day": "يوم",
    "min": "دقيقة",
    "hr": "ساعة",
    "hours": "ساعات",
    "hour": "ساعة",
    "minutes": "دقائق",
    "minute": "دقيقة",
    
    // UserDashboard
    "dashboard": "لوحة التحكم",
    "welcomeBack": "مرحباً بعودتك!",
    "coursesCompleted": "الدورات المكتملة",
    "inProgress": "قيد التنفيذ",
    "hoursWatched": "ساعات المشاهدة",
    "memberSince": "عضو منذ",
    "myCourses": "دوراتي",
    "inProgressTab": "قيد التنفيذ",
    "completedTab": "مكتملة",
    "noCoursesInProgress": "ليس لديك أي دورات قيد التنفيذ بعد\u200E.",
    "noCoursesCompleted": "لم تكمل أي دورات بعد\u200E.",
    "startLearning": "ابدأ التعلم لرؤية تقدمك هنا\u200E!",
    "getStarted": "ابدأ",
    "noCoursesYet": "لا توجد دورات بعد",
    "getStartedDescription": "ابدأ رحلة التعلم الخاصة بك من خلال استكشاف دوراتنا. اكتشف الموضوعات التي تهمك وابدأ طريقك نحو المعرفة.",
    "browseCourses": "تصفح الدورات",
    
    // Navigation
    "home": "الرئيسية",
    "courses": "الدورات",
    "subscription": "الاشتراك",
    "personalTests": "اختبارات شخصية",
    "personalTestsPageTitle": "اكتشفي البرامج المناسبة لك",
    "personalTestsPageSubtitle": "خوضي اختباراً قصيراً واحصلي على توصيات برامج مخصصة بناءً على احتياجاتك.",
    "searchPersonalTests": "البحث في الاختبارات…",
    "searchMyResults": "البحث في نتائجك…",
    "noCompletedTestsMatch": "لا توجد اختبارات مكتملة تطابق بحثك.",
    "recommendedCourseSingular": "دورة موصى بها",
    "recommendedCoursesCount": "دورات موصى بها",
    "noPersonalTestsAvailable": "لا توجد اختبارات متاحة حالياً. عد لاحقاً.",
    "startPersonalTest": "ابدأ الاختبار",
    "testDescription": "الوصف",
    "question": "سؤال",
    "questions": "أسئلة",
    "personalTestNotAvailable": "هذا الاختبار غير متاح.",
    "backToPersonalTests": "العودة إلى الاختبارات",
    "recommendedCourses": "دوراتك الموصى بها",
    "testCompletedTitle": "لقد أكملت الاختبار!",
    "testCompletedSubtitle": "بناءً على إجاباتك، إليك الدورات التي يمكن أن تساعدك أكثر.",
    "topRecommendedCourses": "أفضل الدورات الموصى بها لك",
    "completedIn": "اكتمل خلال {duration}",
    "exploreAllCourses": "استكشف جميع الدورات",
    "chooseOneAnswer": "اختر واحداً",
    "chooseAllAnswers": "اختر كل ما ينطبق",
    "previous": "السابق",
    "next": "التالي",
    "seeResults": "عرض النتائج",
    "savingResults": "جاري حفظ نتائجك…",
    "noCourseRecommendations": "لم تطابق إجاباتك أي توصيات دورات.",
    "retakeTest": "إعادة الاختبار",
    "takeTests": "خوض الاختبارات",
    "availableTestsTab": "الاختبارات المتاحة",
    "myResultsTab": "نتائجي",
    "noCompletedTests": "لم تكمل أي اختبارات بعد.",
    "viewResults": "عرض النتائج",
    "completedOn": "اكتمل",
    "yourAnswers": "إجاباتك",
    "selectedAnswer": "الإجابة المختارة",
    "selectedAnswers": "الإجابات المختارة",
    "noAnswerSelected": "لم يتم اختيار إجابة.",
    "questionProgress": "السؤال {current} من {total}",
    "testProgressComplete": "{percent}% مكتمل",
    "basedOnAnswersTo": "بناءً على إجاباتك في \"{testName}\"",
    "loading": "جاري التحميل…",

    // UserProfile dropdown
    "user": "مستخدم",
    "changePassword": "تغيير كلمة المرور",
    "version": "الإصدار",
    "build": "البناء",
    "signOut": "تسجيل الخروج",
    "signingOut": "جاري تسجيل الخروج…",
    "newPassword": "كلمة المرور الجديدة",
    "confirmNewPassword": "تأكيد كلمة المرور الجديدة",
    "enterNewPassword": "أدخل كلمة المرور الجديدة",
    "confirmNewPasswordPlaceholder": "أكد كلمة المرور الجديدة",
    "cancel": "إلغاء",
    "changing": "جاري التغيير…",
    "pleaseFillPasswordFields": "يرجى تعبئة جميع حقول كلمة المرور",
    "passwordsDoNotMatch": "كلمات المرور الجديدة غير متطابقة",
    "passwordMinLength": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    "passwordChangedSuccess": "تم تغيير كلمة المرور بنجاح",
    "failedToChangePassword": "فشل تغيير كلمة المرور. يرجى المحاولة مرة أخرى.",

    // Payments
    "payments": "المدفوعات",
    "manageSubscriptions": "إدارة الاشتراكات ومعالجة المدفوعات",
    "subscriptionStatusTitle": "حالة الاشتراك",
    "syncing": "جاري المزامنة...",
    "yourSubscriptionInfo": "معلومات الاشتراك الحالية",
    "syncingSubscriptionStatus": "جاري مزامنة حالة الاشتراك من Stripe...",
    "noActiveSubscription": "ليس لديك اشتراك نشط.",
    "subscribeNow": "اشترك الآن",
    "creatingCheckoutSession": "جاري إنشاء جلسة الدفع...",
    "subscriptionActive": "الاشتراك نشط",
    "subscriptionExpired": "الاشتراك منتهي",
    "active": "نشط",
    "trialing": "تجريبي",
    "expired": "منتهي",
    "pastDue": "متأخر",
    "canceled": "ملغى",
    "subscriptionDataNeedsSync": "بيانات الاشتراك تحتاج للمزامنة",
    "subscriptionDatesInvalid": "تواريخ الاشتراك مفقودة أو غير صالحة. انقر على الزر أدناه لمزامنة أحدث البيانات من Stripe.",
    "syncFromStripe": "مزامنة من Stripe",
    "billingCycle": "دورة الفوترة",
    "currentPeriod": "الفترة الحالية",
    "daysRemaining": "الأيام المتبقية",
    "days": "أيام",
    "cycleProgress": "تقدم الدورة",
    "daysElapsed": "أيام منقضية",
    "daysRemainingLabel": "أيام متبقية",
    "scheduledForCancellation": "مجدول للإلغاء",
    "subscriptionEndsOn": "سينتهي اشتراكك في",
    "canReactivateAnytime": "يمكنك إعادة تفعيله في أي وقت قبل ذلك.",
    "reactivateSubscription": "إعادة تفعيل الاشتراك",
    "reactivating": "جاري إعادة التفعيل...",
    "cancelSubscription": "إلغاء الاشتراك",
    "manageInStripe": "إدارة في Stripe",
    "opening": "جاري الفتح...",
    "manageInStripeDescription": "استخدم زر \"إدارة في Stripe\" لتحديث طرق الدفع وعرض سجل الفوترة وإدارة إعدادات الاشتراك الخاصة بك.",
    "cancelSubscriptionTitle": "إلغاء الاشتراك؟",
    "subscriptionRemainsActive": "سيظل اشتراكك نشطًا حتى نهاية فترة الفوترة الحالية.",
    "continueAccessUntil": "ستستمر في الحصول على الوصول حتى",
    "canReactivateBeforePeriod": "يمكنك إعادة تفعيل اشتراكك في أي وقت قبل انتهاء الفترة.",
    "keepSubscription": "الاحتفاظ بالاشتراك",
    "canceling": "جاري الإلغاء...",
    "productPriceManagement": "إدارة المنتج والسعر",
    "subscriptionPlansTitle": "خطط الاشتراك",
    "subscriptionPlansSubtitle": "إدارة خطط الأسعار والوصول للدورات ومعاينة ظهورها للمستخدمين.",
    "createPlan": "إنشاء خطة",
    "pricingPreview": "معاينة الأسعار",
    "editPlan": "تعديل الخطة",
    "createSubscriptionPlan": "إنشاء خطة اشتراك",
    "planBasics": "أساسيات",
    "planAppearance": "المظهر",
    "planCourseAccess": "الوصول للدورات",
    "planInheritance": "الوراثة",
    "planFeatures": "الميزات",
    "planLivePreview": "معاينة مباشرة",
    "planBadgeNone": "بدون",
    "planBadgeStartHere": "ابدأ هنا",
    "planBadgeBestValue": "أفضل قيمة",
    "planBadgeMostPopular": "الأكثر شعبية",
    "planBadgeLimited": "محدود",
    "planBadgeVip": "VIP",
    "planIncludeAllCourses": "تضمين جميع الدورات المنشورة",
    "planIncludeFromPlan": "تضمين كل شيء من الخطة",
    "planUpdatePriceStripe": "تحديث السعر على Stripe",
    "planArchive": "أرشفة الخطة",
    "planSaveChanges": "حفظ التغييرات",
    "planCompareAtPrice": "السعر السابق (اختياري)",
    "planPriceSubtitle": "وصف السعر",
    "planPromotionBadge": "شارة ترويجية",
    "planRibbonText": "نص الشريط (اختياري)",
    "planChecklistItem": "عنصر قائمة تحقق (لتنفيذ الخدمات لاحقًا)",
    "planAddFeature": "إضافة ميزة",
    "adminOnly": "للمشرف فقط",
    "configureStripeProduct": "تكوين منتج وسعر Stripe المراد استخدامهما للاشتراكات",
    "currentConfiguration": "التكوين الحالي",
    "product": "المنتج",
    "price": "السعر",
    "fetchProductsFromStripe": "جلب المنتجات من Stripe",
    "fetchingFromStripe": "جاري الجلب من Stripe...",
    "selectProduct": "اختر المنتج",
    "chooseProduct": "اختر منتجًا",
    "selectPrice": "اختر السعر",
    "choosePrice": "اختر سعرًا",
    "selectMonthlyPrice": "اختر السعر الشهري",
    "chooseMonthlyPrice": "اختر سعرًا شهريًا",
    "selectYearlyPrice": "اختر السعر السنوي",
    "chooseYearlyPrice": "اختر سعرًا سنويًا",
    "monthlyPrice": "السعر الشهري",
    "yearlyPrice": "السعر السنوي",
    "monthly": "شهري",
    "yearly": "سنوي",
    "none": "لا شيء",
    "optional": "اختياري",
    "noMonthlyPrices": "لا توجد أسعار شهرية لهذا المنتج.",
    "noYearlyPrices": "لا توجد أسعار سنوية لهذا المنتج.",
    "pleaseSelectProductAndMonthlyPrice": "يرجى اختيار المنتج والسعر الشهري",
    "noActiveRecurringPrices": "لا توجد أسعار متكررة نشطة لهذا المنتج.",
    "saveConfiguration": "حفظ التكوين",
    "saving": "جاري الحفظ...",
    "noActiveProducts": "لا توجد منتجات نشطة في Stripe. أنشئ المنتجات في لوحة تحكم Stripe أولاً.",
    "subscribe": "اشترك",
    "testSubscription": "اشتراك تجريبي",
    "testStripePaymentFlow": "اختبر عملية الدفع في Stripe مع اشتراك تجريبي. سيتم إعادة توجيهك إلى صفحة الدفع في Stripe.",
    "noProductConfigured": "لم يتم تكوين منتج. يحتاج المشرف إلى تكوين منتج أولاً.",
    "paymentSuccessfulActivated": "تم الدفع بنجاح! تم تفعيل اشتراكك.",
    "paymentSuccessfulActivating": "تم الدفع بنجاح! جاري تفعيل اشتراكك...",
    "paymentSuccessfulSyncFailed": "تم الدفع بنجاح، ولكن فشلت مزامنة حالة الاشتراك. يرجى تحديث الصفحة.",
    "paymentCanceled": "تم إلغاء الدفع. يمكنك المحاولة مرة أخرى في أي وقت.",
    "failedToCreateCheckoutSession": "فشل إنشاء جلسة الدفع",
    "failedToCreateCheckoutSessionRetry": "فشل إنشاء جلسة الدفع. يرجى المحاولة مرة أخرى.",
    "failedToCancelSubscription": "فشل إلغاء الاشتراك. يرجى المحاولة مرة أخرى.",
    "failedToReactivateSubscription": "فشل إعادة تفعيل الاشتراك. يرجى المحاولة مرة أخرى.",
    "failedToOpenCustomerPortal": "فشل فتح بوابة العملاء",
    "failedToOpenCustomerPortalRetry": "فشل فتح بوابة العملاء. يرجى المحاولة مرة أخرى.",
    "subscriptionAdminGrantedContactSupport": "تم منح اشتراكك من قبل المشرف. لتغييره، تواصل مع الدعم.",
    "noSubscriptionFoundToSync": "لم يتم العثور على اشتراك للمزامنة",
    "subscriptionDataSyncedSuccessfully": "تمت مزامنة بيانات الاشتراك بنجاح",
    "failedToSyncSubscription": "فشلت مزامنة الاشتراك. يرجى المحاولة مرة أخرى.",
    "failedToFetchProducts": "فشل جلب المنتجات من Stripe",
    "pleaseSelectProductAndPrice": "يرجى اختيار المنتج والسعر معًا",
    "selectedProductOrPriceNotFound": "المنتج أو السعر المحدد غير موجود",
    "paymentSettingsSavedSuccessfully": "تم حفظ إعدادات الدفع بنجاح",
    "failedToSavePaymentSettings": "فشل حفظ إعدادات الدفع",
    "for": "لـ",
    "noActivePrices": "لا توجد أسعار نشطة",
    "subscribeToProduct": "اشترك في {productName} مقابل {price} لكل {interval}",
    "chooseBillingCycle": "اختر دورة الفوترة",
    "mostPopular": "الأكثر شعبية",
    "bestValue": "أفضل قيمة",

    // Login
    "loginTitle": "تسجيل الدخول إلى رهام ديفا",
    "loginCreateAccountTitle": "إنشاء حساب",
    "loginResetPasswordTitle": "إعادة تعيين كلمة المرور",
    "loginEnterResetCodeTitle": "أدخل رمز إعادة التعيين",
    "loginWithGoogle": "تسجيل الدخول عبر Google",
    "loginOr": "أو",
    "loginEmail": "البريد الإلكتروني",
    "loginName": "الاسم",
    "loginPassword": "كلمة المرور",
    "loginNewPassword": "كلمة المرور الجديدة",
    "loginResetCode": "رمز إعادة التعيين",
    "loginForgotPassword": "نسيت كلمة المرور؟",
    "loginEmailPlaceholder": "example@email.com",
    "loginNamePlaceholder": "الاسم الكامل",
    "loginPasswordPlaceholder": "••••••••••••",
    "loginResetCodePlaceholder": "12345678",
    "loginSendingCode": "جاري إرسال الرمز…",
    "loginSendResetCode": "إرسال رمز إعادة التعيين",
    "loginResettingPassword": "جاري إعادة تعيين كلمة المرور…",
    "loginResetPassword": "إعادة تعيين كلمة المرور",
    "loginRedirecting": "جاري إعادة التوجيه…",
    "loginCreatingAccount": "جاري إنشاء الحساب…",
    "loginSigningIn": "جاري تسجيل الدخول…",
    "loginCreateAccount": "إنشاء حساب",
    "loginLogIn": "تسجيل الدخول",
    "loginResetEmailInfo": "إذا كان بريدك الإلكتروني مسجلاً لدينا، فستتلقى رسالة لإعادة تعيين كلمة المرور قريباً.",
    "loginResetCodeHint": "أدخل الرمز المكوّن من 8 أرقام المرسل إلى {email}",
    "loginPasswordMinLength": "8 أحرف على الأقل",
    "loginPasswordUppercase": "حرف كبير واحد على الأقل",
    "loginPasswordLowercase": "حرف صغير واحد على الأقل",
    "loginPasswordNumber": "رقم واحد على الأقل",
    "loginPasswordResetSuccess": "تمت إعادة تعيين كلمة المرور بنجاح. جاري إعادة التوجيه…",
    "loginAccountCreatedRedirecting": "تم إنشاء الحساب. جاري إعادة التوجيه…",
    "loginSignedInRedirecting": "تم تسجيل الدخول. جاري إعادة التوجيه…",
    "loginNoAccount": "ليس لديك حساب؟ ",
    "loginHasAccount": "لديك حساب بالفعل؟ ",
    "loginSignUp": "إنشاء حساب",
    "loginLogInLink": "تسجيل الدخول",
    "loginTermsPrefix": "بتسجيل الدخول، فإنك توافق على ",
    "loginTerms": "الشروط",
    "loginAnd": " و",
    "loginPrivacyPolicy": "سياسة الخصوصية",
    "loginErrorInvalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة. يرجى التحقق والمحاولة مرة أخرى.",
    "loginErrorEmailNotFound": "لا يوجد حساب بهذا البريد الإلكتروني. يرجى التحقق من بريدك والمحاولة مرة أخرى.",
    "loginErrorWrongPassword": "كلمة المرور غير صحيحة. يرجى التحقق من كلمة المرور والمحاولة مرة أخرى.",
    "loginErrorDeactivated": "تم إيقاف هذا الحساب. يرجى التواصل مع الدعم للمساعدة.",
    "loginErrorUnauthorized": "غير مصرح لك بالوصول إلى هذا الحساب. يرجى التواصل مع الدعم.",
    "loginErrorEmailExists": "يوجد حساب بهذا البريد الإلكتروني بالفعل. يرجى تسجيل الدخول بدلاً من ذلك.",
    "loginErrorInvalidResetCode": "رمز إعادة التعيين غير صالح أو منتهي الصلاحية. يرجى التحقق من الرمز أو طلب رمز جديد.",
    "loginErrorResetCodeExpired": "انتهت صلاحية رمز إعادة التعيين. يرجى طلب رمز جديد.",
    "loginErrorSignInFailed": "فشل تسجيل الدخول. يرجى التحقق من بريدك الإلكتروني وكلمة المرور والمحاولة مرة أخرى.",
    "loginErrorRegisterFailed": "فشل إنشاء الحساب. يرجى المحاولة مرة أخرى أو التواصل مع الدعم إذا استمرت المشكلة.",
    "loginErrorGeneric": "حدث خطأ. يرجى المحاولة مرة أخرى أو التواصل مع الدعم إذا استمرت المشكلة.",
    "loginErrorUnexpected": "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    "loginErrorGoogleSignIn": "فشل تسجيل الدخول عبر Google. يرجى المحاولة مرة أخرى.",
    "loginErrorPasswordRequirements": "كلمة المرور لا تستوفي المتطلبات. يرجى مراجعة متطلبات كلمة المرور أعلاه.",
    "loginErrorWrongResetCode": "رمز إعادة التعيين غير صحيح.",
  },
} as const;

export function useLanguage() {
  const [searchParams, setSearchParams] = useSearchParams();
  
  const language = useMemo<Language>(() => {
    const lang = searchParams.get("lang");
    return lang === "ar" ? "ar" : DEFAULT_LANGUAGE;
  }, [searchParams]);

  const setLanguage = useCallback(
    (lang: Language) => {
      const newParams = new URLSearchParams(searchParams);
      if (lang === DEFAULT_LANGUAGE) {
        newParams.delete("lang");
      } else {
        newParams.set("lang", lang);
      }
      setSearchParams(newParams, { replace: true });
    },
    [searchParams, setSearchParams]
  );

  const t = useCallback(
    (key: keyof typeof translations.en): string => {
      return translations[language][key] || translations.en[key];
    },
    [language]
  );

  const localizedPath = useCallback(
    (path: string) => {
      if (language === DEFAULT_LANGUAGE) {
        return path;
      }

      const [pathname, search = ""] = path.split("?");
      const params = new URLSearchParams(search);
      params.set("lang", language);
      const query = params.toString();
      return query ? `${pathname}?${query}` : pathname;
    },
    [language],
  );

  const localizedSiteUrl = useCallback(
    (path = "") => getLocalizedSiteUrl(language, path),
    [language],
  );

  const translateInterval = useCallback(
    (interval: string): string => {
      const normalizedInterval = interval.toLowerCase();
      const key = normalizedInterval as keyof typeof translations.en;
      if (key in translations.en) {
        return translations[language][key];
      }
      return interval; // Fallback to original if not found
    },
    [language]
  );

  return {
    language,
    setLanguage,
    t,
    localizedPath,
    localizedSiteUrl,
    translateInterval,
    isRTL: language === "ar",
  };
}

